# ==============================================================================
# File        : inventory.ini
# Description : Target host inventory reference template for lab automation
# Author      : SudoShea
# Version     : 1.0.0
# Licence     : MIT
# ==============================================================================

[home_server]
# Replace with your RHEL server IP address or local DNS hostname
home-server.local ansible_host=<ip_address>  ansible_user=<user>

[home_server:vars]
ansible_connection=ssh
ansible_python_interpreter=/usr/bin/python3
ansible_become=true
